# Regularization with SciKit-Learn

Regularization attempts to minimize the RSS (residual sum of squares) *and* a penalty factor. This penalty factor will penalize models that have coefficients that are too large. Some methods of regularization will actually cause non useful features to have a coefficient of zero, in which case the model does not consider the feature.

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
from google.colab import drive
drive.mount('/content/gdrive')

Mounted at /content/gdrive


In [3]:
df = pd.read_csv('gdrive/My Drive/csv_files/Advertising.csv')

In [4]:
df.head()

TV  radio  newspaper  sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3    9.3
3  151.5   41.3       58.5   18.5
4  180.8   10.8       58.4   12.9

In [5]:
X = df.drop('sales',axis=1)

In [6]:
y = df['sales']

### Polynomial Conversion

In [7]:
from sklearn.preprocessing import PolynomialFeatures

In [8]:
polynomial_converter = PolynomialFeatures(degree=3,include_bias=False)

In [9]:
poly_features = polynomial_converter.fit_transform(X)

In [10]:
X.shape

(200, 3)

In [11]:
poly_features.shape

(200, 19)

### Train | Test Split

In [12]:
from sklearn.model_selection import train_test_split

In [13]:
X_train, X_test, y_train, y_test = train_test_split(poly_features, y, test_size=0.3, random_state=101)

In [14]:
X_train.shape

(140, 19)

----
----

## Scaling the Data

In [15]:
from sklearn.preprocessing import StandardScaler

In [16]:
scaler = StandardScaler()

In [17]:
scaler.fit(X_train)

StandardScaler()

In [18]:
X_train = scaler.transform(X_train)

In [19]:
X_test = scaler.transform(X_test)

In [20]:
X_train[0]

array([ 0.49300171, -0.33994238,  1.61586707,  0.28407363, -0.02568776,
        1.49677566, -0.59023161,  0.41659155,  1.6137853 ,  0.08057172,
       -0.05392229,  1.01524393, -0.36986163,  0.52457967,  1.48737034,
       -0.66096022, -0.16360242,  0.54694754,  1.37075536])

In [21]:
poly_features[0]

array([2.30100000e+02, 3.78000000e+01, 6.92000000e+01, 5.29460100e+04,
       8.69778000e+03, 1.59229200e+04, 1.42884000e+03, 2.61576000e+03,
       4.78864000e+03, 1.21828769e+07, 2.00135918e+06, 3.66386389e+06,
       3.28776084e+05, 6.01886376e+05, 1.10186606e+06, 5.40101520e+04,
       9.88757280e+04, 1.81010592e+05, 3.31373888e+05])

## Ridge Regression

In [22]:
from sklearn.linear_model import Ridge

In [23]:
#help(Ridge)

In [24]:
ridge_model = Ridge(alpha=10)

In [25]:
ridge_model.fit(X_train,y_train)

Ridge(alpha=10)

In [26]:
test_predictions = ridge_model.predict(X_test)

In [27]:
from sklearn.metrics import mean_absolute_error,mean_squared_error

In [28]:
MAE = mean_absolute_error(y_test,test_predictions)

In [29]:
MAE

0.5774404204714162

In [30]:
RMSE = np.sqrt(mean_squared_error(y_test,test_predictions))

In [31]:
RMSE

0.8946386461319651

### Choosing an alpha value with Cross-Validation


In [32]:
from sklearn.linear_model import RidgeCV       # Ridge Cross Validation 

In [33]:
ridge_cv_model = RidgeCV(alphas= (0.1, 1, 10))

In [34]:
ridge_cv_model.fit(X_train,y_train)

RidgeCV(alphas=array([ 0.1,  1. , 10. ]))

In [35]:
ridge_cv_model.alpha_

0.1

In [36]:
from sklearn.metrics import SCORERS

In [37]:
SCORERS.keys()

dict_keys(['explained_variance', 'r2', 'max_error', 'neg_median_absolute_error', 'neg_mean_absolute_error', 'neg_mean_absolute_percentage_error', 'neg_mean_squared_error', 'neg_mean_squared_log_error', 'neg_root_mean_squared_error', 'neg_mean_poisson_deviance', 'neg_mean_gamma_deviance', 'accuracy', 'top_k_accuracy', 'roc_auc', 'roc_auc_ovr', 'roc_auc_ovo', 'roc_auc_ovr_weighted', 'roc_auc_ovo_weighted', 'balanced_accuracy', 'average_precision', 'neg_log_loss', 'neg_brier_score', 'adjusted_rand_score', 'rand_score', 'homogeneity_score', 'completeness_score', 'v_measure_score', 'mutual_info_score', 'adjusted_mutual_info_score', 'normalized_mutual_info_score', 'fowlkes_mallows_score', 'precision', 'precision_macro', 'precision_micro', 'precision_samples', 'precision_weighted', 'recall', 'recall_macro', 'recall_micro', 'recall_samples', 'recall_weighted', 'f1', 'f1_macro', 'f1_micro', 'f1_samples', 'f1_weighted', 'jaccard', 'jaccard_macro', 'jaccard_micro', 'jaccard_samples', 'jaccard_wei

In [38]:
ridge_cv_model = RidgeCV(alphas= (0.1, 1, 10),scoring='neg_mean_squared_error')

In [39]:
ridge_cv_model.fit(X_train,y_train)

RidgeCV(alphas=array([ 0.1,  1. , 10. ]), scoring='neg_mean_squared_error')

In [40]:
ridge_cv_model.alpha_

0.1

In [41]:
test_predictions = ridge_cv_model.predict(X_test)

In [42]:
MAE = mean_absolute_error(y_test,test_predictions)

In [43]:
RMSE = np.sqrt(mean_squared_error(y_test,test_predictions))

In [44]:
MAE

0.4273774884345441

In [45]:
RMSE

0.6180719926946004

In [46]:
ridge_cv_model.coef_

array([ 5.40769392,  0.5885865 ,  0.40390395, -6.18263924,  4.59607939,
       -1.18789654, -1.15200458,  0.57837796, -0.1261586 ,  2.5569777 ,
       -1.38900471,  0.86059434,  0.72219553, -0.26129256,  0.17870787,
        0.44353612, -0.21362436, -0.04622473, -0.06441449])

In [47]:
ridge_cv_model.best_score_

-0.37770668487073494


-----

## LASSO Regression

LASSO - Least Absolute Shrinkage and Selection Operator

In [48]:
from sklearn.linear_model import LassoCV

In [49]:
lasso_cv_model = LassoCV(eps=0.1, n_alphas=100,cv=5)

In [50]:
lasso_cv_model.fit(X_train,y_train)

LassoCV(cv=5, eps=0.1)

In [51]:
lasso_cv_model.alpha_

0.4943070909225832

In [52]:
test_predictions = lasso_cv_model.predict(X_test)

In [53]:
MAE = mean_absolute_error(y_test,test_predictions)

In [54]:
RMSE = np.sqrt(mean_squared_error(y_test,test_predictions))

In [55]:
MAE

0.6541723161252867

In [56]:
RMSE

1.1308001022762548

In [57]:
lasso_cv_model.coef_

array([1.002651  , 0.        , 0.        , 0.        , 3.79745279,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        ])

In [58]:
lasso_cv_model = LassoCV(eps=0.001, n_alphas=100,cv=5,max_iter=1000000)

In [59]:
lasso_cv_model.fit(X_train,y_train)

LassoCV(cv=5, max_iter=1000000)

In [60]:
lasso_cv_model.alpha_

0.004943070909225833

In [61]:
test_predictions = lasso_cv_model.predict(X_test)

In [62]:
MAE = mean_absolute_error(y_test,test_predictions)

In [63]:
RMSE = np.sqrt(mean_squared_error(y_test,test_predictions))

In [64]:
MAE

0.4335034618590078

In [65]:
RMSE

0.6063140748984043

In [66]:
lasso_cv_model.coef_

array([ 4.86023329,  0.12544598,  0.20746872, -4.99250395,  4.38026519,
       -0.22977201, -0.        ,  0.07267717, -0.        ,  1.77780246,
       -0.69614918, -0.        ,  0.12044132, -0.        , -0.        ,
       -0.        ,  0.        ,  0.        , -0.        ])

## Elastic Net

Elastic Net combines the penalties of ridge regression and lasso in an attempt to get the best of both worlds!

In [67]:
from sklearn.linear_model import ElasticNetCV

In [68]:
elastic_model = ElasticNetCV(l1_ratio=[.1, .5, .7,.9, .95, .99, 1],eps=0.001,n_alphas=100,max_iter=1000000)

In [69]:
elastic_model.fit(X_train,y_train)

ElasticNetCV(l1_ratio=[0.1, 0.5, 0.7, 0.9, 0.95, 0.99, 1], max_iter=1000000)

In [70]:
elastic_model.l1_ratio

[0.1, 0.5, 0.7, 0.9, 0.95, 0.99, 1]

In [71]:
elastic_model.l1_ratio_

1.0

In [73]:
elastic_model.alpha_

0.004943070909225833

In [74]:
lasso_cv_model.alpha_

0.004943070909225833

In [76]:
test_predictions = elastic_model.predict(X_test)

In [77]:
MAE = mean_absolute_error(y_test,test_predictions)

In [78]:
MAE

0.4335034618590078